spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: microservicecloud-config-atguigu-dev111
---
spring:
  profiles: test   #测试环境
  application: 
    name: microservicecloud-config-atguigu-test111
#  请保存为UTF-8格式
